site_name: Sveltos Documentation
copyright: Copyright &copy; 2022
theme:
  name: material
  logo: assets/images/logo.png
nav:
  - Home: index.md
  - Introduction: introduction.md
  - Getting Started: getting-started.md
  - Configuration: configuration.md
  - Contributing: contributing.md
  - License: license.md